name 'puppet-splunkstorm'
version '0.0.1'
license 'Apache 2.0'
summary 'Report processor that sends logs and metrics as events to SplunkStorm'
project_page 'https://github.com/jamtur01/puppet-splunkstorm'
